[package]
name = "craft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gosyn = "0.2.5"
base64 = "0.21.5"
indicatif = "0.17.7"