// Code generated by craft; DO NOT EDIT.

package example

import (
	"github.com/go-playground/validator/v10"
)

var validate_Li90ZXN0cy9leGFtcGxlL2V4YW1wbGUyLmdv = validator.New(validator.WithRequiredStructEnabled())
