// Code generated by craft; DO NOT EDIT.

package example

import (
	"context"
	"errors"
	"github.com/go-playground/validator/v10"
	"git.5th.im/lb-public/gear/util/metautil"
)

var validate_example = validator.New(validator.WithRequiredStructEnabled())

type Hello_NameError struct{}

func (Hello_NameError) Trans(ctx context.Context) error {
	switch metautil.Language(ctx) {
	case "zh-HK":
		return errors.New("參數錯誤，名稱不能為空")
	case "zh-CN":
		return errors.New("参数错误，名称不能为空")
	case "en":
		return errors.New("Parameter error, name cannot be empty")
	default:
		return errors.New("參數錯誤，名稱不能為空")
	}
}

func (h *Hello) Validate(ctx context.Context) error {
	if err := validate_example.Var(h.Name,"required,email,gte=0,lte=130,iscolor,oneof=male female prefer_not_to"); err != nil {
		return Hello_NameError.Trans(struct{}{},ctx)
	}

	if err := validate_example.Var(h.Age,"required"); err != nil {
		return err
	}


	return nil
}

