// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/card.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"

	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf
var _ = proto.Marshal

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Card service

type CardService interface {
	GetCardInfo(ctx context.Context, in *GetCardInfoReq, opts ...client.CallOption) (*GetCardInfoResp, error)
}

type cardService struct {
	c    client.Client
	name string
}

func NewCardService(name string, c client.Client) CardService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &cardService{
		c:    c,
		name: name,
	}
}

func (c *cardService) GetCardInfo(ctx context.Context, in *GetCardInfoReq, opts ...client.CallOption) (*GetCardInfoResp, error) {
	req := c.c.NewRequest(c.name, "/proto.Card/GetCardInfo", in)
	out := new(GetCardInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Card service

type CardHandler interface {
	GetCardInfo(context.Context, *GetCardInfoReq, *GetCardInfoResp) error
}

func RegisterCardHandler(s server.Server, hdlr CardHandler, opts ...server.HandlerOption) error {
	opts = append(opts, _Card_serviceDesc_handlerOptions)
	type card interface {
		GetCardInfo(ctx context.Context, in *GetCardInfoReq, out *GetCardInfoResp) error
	}
	type Card struct {
		card
	}
	h := &cardHandler{hdlr}
	return s.Handle(s.NewHandler(&Card{h}, opts...))
}

type cardHandler struct {
	CardHandler
}

func (h *cardHandler) GetCardInfo(ctx context.Context, in *GetCardInfoReq, out *GetCardInfoResp) error {
	return h.CardHandler.GetCardInfo(ctx, in, out)
}

var _Card_serviceDesc_handlerOptions = func(options *server.HandlerOptions) {
	options.Metadata[".serviceDesc"] = map[string]string{
		"protoPath":   "proto/card.proto",
		"serviceName": "proto.Card",
	}
}
