// Code generated by protoc-gen-zaplog. DO NOT EDIT.
// source: proto/card.proto

package proto

import (
	"github.com/spf13/cast"
	"go.uber.org/zap/zapcore"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = cast.ToString
	_ = durationpb.Duration{}
	_ = emptypb.Empty{}
	_ = timestamppb.Timestamp{}
	_ = wrapperspb.BoolValue{}
)

func (m *GetCardInfoReq) MarshalLogObject(enc zapcore.ObjectEncoder) error {

	if v := m.GetCardId(); v != "" {
		enc.AddString("card_id", v)
	}

	if v := m.GetFirstName(); v != "" {
		enc.AddString("first_name", v)
	}

	if v := m.GetLastName(); v != "" {
		enc.AddString("last_name", v)
	}

	if v := m.GetAge(); v != 0 {
		enc.AddUint32("age", v)
	}

	if v := m.GetEmail(); v != "" {
		enc.AddString("email", v)
	}

	if v := m.GetGender(); v != "" {
		enc.AddString("gender", v)
	}

	if v := m.GetColor(); v != "" {
		enc.AddString("color", v)
	}

	return nil
}

func (m *GetCardInfoResp) MarshalLogObject(enc zapcore.ObjectEncoder) error {

	return nil
}
